# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
