# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_area_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='area_interesse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social.Area'),
            preserve_default=False,
        ),
    ]
