# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_connection_area_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[(0, 'Pendente'), (1, 'Ativa'), (2, 'Inativa')], default=0, max_length=10),
        ),
    ]
