# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Ativa', 'Ativa'), ('Inativa', 'Inativa')], default='Pendente', max_length=10),
        ),
    ]
